name: Build and Release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Node & NPM version
        run: node -v && npm -v

      - name: Install dependencies
        run: npm install --verbose
        env:
          ELECTRON_MIRROR: https://cdn.npmmirror.com/binaries/electron/

      - name: Build Windows executable
        run: npm run build:win
        env:
          ELECTRON_MIRROR: https://cdn.npmmirror.com/binaries/electron/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List dist
        run: dir dist\ /s
        if: always()

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: MechvibesPlusPlus-Windows
          path: dist/
          retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MechvibesPlusPlus-Windows
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
